if (!require("shiny")) install.packages("shiny")
if (!require("shinydashboard")) install.packages("shinydashboard")
if (!require("DT")) install.packages("DT")
if (!require("dplyr")) install.packages("dplyr")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("vcfR")) install.packages("vcfR")
if (!require("readr")) install.packages("readr")
if (!require("ggsurvfit")) install.packages("ggsurvfit")
if (!require("survival")) install.packages("survival")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("survminer")) install.packages("survminer")
if (!require("lubridate")) install.packages("lubridate")
if (!require("gtsummary")) install.packages("gtsummary")
library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)
library(tidyverse)
library(vcfR)
library(readr)
library(readxl)
library(ggsurvfit)
library(survival)
library(ggplot2)
library(survminer)
library(lubridate)
library(gtsummary)
